assets_path: data/assets
cubicasa_dataset_path: data/cubicasa_dataset
g_dataset_path: data/g_dataset
ig_dataset_path: data/ig_dataset
key_path: data/igibson.key
threedfront_dataset_path: data/threedfront_dataset
