max_obstacle_height: 0.60  # assume something like an arm is mounted on top of the robot

# Obstacle Cost Shaping (http://wiki.ros.org/costmap_2d/hydro/inflation)
robot_radius: 0.20  # distance a circular robot should be clear of the obstacle (kobuki: 0.18)
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]  # if the robot is not circular

map_type: voxel

#obstacle_layer:
#  enabled: true
#  origin_z: 0.0
#  z_resolution: 0.05
#  z_voxels: 10
#  unknown_threshold: 0
#  #mark_threshold: 2
#  publish_voxel_map: true
#  combination_method: 1
#  observation_sources: points
#  points:
#    data_type: PointCloud2
#    topic: robot1/gibson_ros/lidar/points
#    marking: true
#    clearing: true
#    obstacle_range: 1.90
#    raytrace_range: 2.00
#    min_obstacle_height: 0.15
#    max_obstacle_height: 0.6
#    mark_threshold: 3
#    observation_persistence: 2.0

  # for debugging only, let's you see the entire voxel grid

#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation:
    enabled:              true
    cost_scaling_factor:  5.0  # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius:     0.2  # max. distance from an obstacle at which costs are incurred for planning paths.

static:
    map_topic: robot1/map
    subscribe_to_updates: true
    #enabled:              false

obstacle_range: 1.90
raytrace_range: 2.00
resolution: 0.05
robot_base_frame: robot1/base_link
publish_frequency: 5.0

obstacles_laser:
    enabled: true
    origin_z: 0.0
    z_resolution: 0.05
    z_voxels: 10
    unknown_threshold: 0
    publish_voxel_map: true
    combination_method: 1
    obstacle_range: 1.90
    raytrace_range: 2.00
    z_resolution: 0.05
    resolution: 0.05
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /robot1/gibson_ros/laserscan, inf_is_valid: false}


#footprint: [[-0.2, -0.2], [-0.2, 0.2], [0.2, 0.2], [0.2, -0.2]]
#footprint_padding: 0.01

#update_frequency: 5.0
#publish_frequency: 5.0
#transform_tolerance: 0.2

#resolution: 0.05

#obstacle_range: 10.0
#raytrace_range: 10.0

#layer definitions
#static:
#    map_topic: robot1/map
#    subscribe_to_updates: true

#obstacles_laser:
#    observation_sources: laser
#    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /robot1/gibson_ros/laserscan, inf_is_valid: false}

#inflation:
#    inflation_radius: 0.2